apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/abin-tiger/sample-rest-api:main
        env:
        - name: TARGET
          value: "Python Sample v1"
