apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/metric: "rps"
        # autoscaling.knative.dev/initial-scale: "0"
        autoscaling.knative.dev/scale-down-delay: "10s"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "100"
    spec:
      containerConcurrency: 10
      containers:
      - image: ghcr.io/abin-tiger/sample-rest-api:main
        imagePullPolicy: Always
        env:
        - name: TARGET
          value: "Python Sample v1"
